name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  GO111MODULE: "on"
jobs:
  testBackportSupport:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVersion: [1.24.x, 1.23.x, 1.22.x, 1.21.x, 1.19.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go ${{matrix.goVersion}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.goVersion}}

      - name: Format & vet
        run: |
          diff <(gofmt -d .) <(echo -n)
          go vet -x ./...
      - name: Install & run golint
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./...

      - name: Run tests
        run: go test -v -race ./...